apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-app
  namespace: starbucks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starbucks-app
  template:
    metadata:
      labels:
        app: starbucks-app
    spec:
      containers:
      - name: starbucks-app
        image: harsh601/starbucks-clone:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "20m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
