apiVersion: v1
kind: Service
metadata:
  name: starbucks-service
  namespace: starbucks
spec:
  selector:
    app: starbucks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer   